Skip the error caused by failed connection
The error message is like:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./run.py", line 85, in work
    oldCycles = ResetInfo["TotalCyclesStat"]
TypeError: 'NoneType' object is not subscriptable